import "./globals.css";

import type { Metadata } from "next";
import { Poppins as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";
import { Footer } from "@/components/footer";

const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Sudip Biswas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          fontSans.variable,
          "relative text-foreground font-sans min-h-screen antialiased"
        )}
      >
        <div className="grid_background" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
